### ISSUE TITLE
feat: Record to toml file

### ISSUE THREAD

**Issue by haruki7049** [haruki7049/kakei#5]
# Related links

https://serde.rs/

# Additional comment

example:
```toml
[expenses]
sushi = { price = 500, unit = "yen" }

[incomes]
pocket_money = { price = 5000, unit = "yen" }
```
